"""
Insight extraction for RB2AE - Expert Secrets (Russell Brunson)
"""
import json, pathlib
from datetime import datetime

SOURCE_ID = "RB2AE"
SOURCE_PERSON = "Russell Brunson"
SOURCE_TITLE = "Expert Secrets"

BASE_DIR = pathlib.Path(__file__).resolve().parent.parent.parent
INSIGHTS_PATH = BASE_DIR / "processing/insights/INSIGHTS-STATE.json"

insights = [
  {"id": f"INS-{SOURCE_ID}-001", "titulo": "Mass Movement Framework - 3 Elementos", "insight": "Todo grande movimento de massa e construido sobre 3 pilares: (1) Lider Carismatico/Attractive Character; (2) A Causa - razao futura para existir alem de vender produto; (3) Nova Oportunidade - veiculo de mudanca diferente de tudo que existe. Sem os 3 nao ha movimento, apenas audiencia passiva.", "priority": "HIGH", "confidence": 0.95, "tags": ["[FRAMEWORK]", "MARKETING", "MOVIMENTO"], "chunks": [f"chunk_{SOURCE_ID}_007", f"chunk_{SOURCE_ID}_008"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[FRAMEWORK]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-002", "titulo": "Perfect Webinar Framework - 5 Elementos", "insight": "O Perfect Webinar segue: (1) Big Domino - uma crenca a derrubar; (2) 3 Segredos - historias de Epiphany Bridge que quebram 3 falsas crencas (veiculo, interno, externo); (3) O Stack - empilhamento de valor com preco ancora; (4) Trial Closes - micro-compromissos; (5) Urgencia/Escassez - bonus exclusivo no pitch. Script que gerou centenas de milhoes para Brunson.", "priority": "HIGH", "confidence": 0.95, "tags": ["[FRAMEWORK]", "VENDAS", "WEBINAR"], "chunks": [f"chunk_{SOURCE_ID}_072", f"chunk_{SOURCE_ID}_073", f"chunk_{SOURCE_ID}_074"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[FRAMEWORK]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-003", "titulo": "Epiphany Bridge - Contar Historias para Criar Crenca", "insight": "Em vez de logica e argumento, use historias de Epiphany Bridge: conte o momento exato em que voce teve o aha moment que quer que a audiencia tenha. A historia leva pessoas a sua propria epifania. Regra: se voce vende com argumento, voce esta errado. Se conta historia e eles chegam a conclusao sozinhos, voce esta certo.", "priority": "HIGH", "confidence": 0.93, "tags": ["[METODOLOGIA]", "STORYTELLING", "COPYWRITING"], "chunks": [f"chunk_{SOURCE_ID}_049", f"chunk_{SOURCE_ID}_050", f"chunk_{SOURCE_ID}_051"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[METODOLOGIA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-004", "titulo": "Big Domino - Uma Crenca que Torna Todas as Outras Irrelevantes", "insight": "Cada produto tem UM Big Domino - uma crenca central que, se derrubada, faz todas as objecoes cairerem. Formato: Se eu conseguir fazer as pessoas acreditarem que [X] e a chave para [resultado] e que so e possivel atraves de [minha solucao], entao todas as outras objecoes se tornam irrelevantes. Mais de um ponto a provar = conversao cai pela metade.", "priority": "HIGH", "confidence": 0.95, "tags": ["[HEURISTICA]", "COPYWRITING", "VENDAS"], "chunks": [f"chunk_{SOURCE_ID}_047", f"chunk_{SOURCE_ID}_048"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[HEURISTICA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-005", "titulo": "Nova Oportunidade vs Oferta de Melhoria", "insight": "Pessoas compram Nova Oportunidade, nao melhoria do que ja existe. Oferta de melhoria diz faca isso melhor; nova oportunidade diz existe um caminho completamente diferente que voce nao tentou. Melhoria forca o prospect a admitir que estava errado. Nova Oportunidade da permissao para recomectar sem culpa. E o posicionamento mais poderoso em marketing.", "priority": "HIGH", "confidence": 0.95, "tags": ["[FILOSOFIA]", "POSICIONAMENTO", "MARKETING"], "chunks": [f"chunk_{SOURCE_ID}_034", f"chunk_{SOURCE_ID}_035"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[FILOSOFIA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-006", "titulo": "Expert Business - Melhor Modelo de Negocio para Comecar", "insight": "Negocio de expert (info-produtos, coaching, consulting) e o modelo com menor barreira de entrada e maior upside: sem capital externo, sem estoque - apenas paixao por ensinar e habilidade de contar historias. O ativo central e a expertise que voce ja tem. O produto e transformar experiencia em ensinamento estruturado.", "priority": "HIGH", "confidence": 0.88, "tags": ["[FILOSOFIA]", "NEGOCIO", "MODELO"], "chunks": [f"chunk_{SOURCE_ID}_006", f"chunk_{SOURCE_ID}_007"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[FILOSOFIA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-007", "titulo": "Heros Two Journeys - Jornada Externa e Transformacao Interna", "insight": "Todo storytelling poderoso tem DUAS jornadas: (1) Jornada Externa - resultado tangivel que o heroi busca; (2) Jornada Interna - transformacao de identidade durante a jornada. Conflito gera emocao. Sem conflito aparentemente intransponivel, a audiencia nao se importa. A transformacao interna e o que o heroi realmente deseja.", "priority": "HIGH", "confidence": 0.90, "tags": ["[MODELO-MENTAL]", "STORYTELLING", "COPYWRITING"], "chunks": [f"chunk_{SOURCE_ID}_058", f"chunk_{SOURCE_ID}_059"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[MODELO-MENTAL]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-008", "titulo": "Certeza Como Veiculo de Transmissao de Crenca", "insight": "O unico jeito de criar crenca em outra pessoa e primeiro ter certeza absoluta voce mesmo. Certeza e transferivel - ela vaza como voce fala, escreve e se posiciona. Expert incerto cria audiencia incerta. Expert com conviccao cria seguidores. A missao e encontrar sua voz pela publicacao e repeticao constante.", "priority": "HIGH", "confidence": 0.88, "tags": ["[MODELO-MENTAL]", "LIDERANCA", "POSICIONAMENTO"], "chunks": [f"chunk_{SOURCE_ID}_018", f"chunk_{SOURCE_ID}_019"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[MODELO-MENTAL]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-009", "titulo": "Status e Polarizacao - O Que Atrai Verdadeiros Fas", "insight": "Pessoas compram quando percebem que a compra vai aumentar seu status. O expert deve carregar a balanca: elevar percepcao de status do lado da compra e diminuir risco do lado oposto. Mensagens polarizadoras atraem seguidores apaixonados - neutralidade nao vende. Expert deve ter posicao clara e polemica dentro do nicho.", "priority": "HIGH", "confidence": 0.87, "tags": ["[MODELO-MENTAL]", "POSICIONAMENTO", "PERSUASAO"], "chunks": [f"chunk_{SOURCE_ID}_033", f"chunk_{SOURCE_ID}_034"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[MODELO-MENTAL]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-010", "titulo": "Regra dos 3 Tipos de Falsas Crencas - Veiculo, Interno, Externo", "insight": "Ha exatamente 3 tipos de falsas crencas que impedem compra mesmo quando o prospect quer o resultado: (1) VEICULO - nao acredita que este metodo funciona; (2) INTERNO - nao acredita que ELE MESMO consegue executar; (3) EXTERNO - nao acredita que condicoes externas (tempo, dinheiro, mercado) permitem. A apresentacao DEVE quebrar as 3, nessa ordem.", "priority": "HIGH", "confidence": 0.95, "tags": ["[HEURISTICA]", "VENDAS", "OBJECOES"], "chunks": [f"chunk_{SOURCE_ID}_067", f"chunk_{SOURCE_ID}_068"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[HEURISTICA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-011", "titulo": "The Stack - Empilhar Valor para Tornar a Oferta Irresistivel", "insight": "O Stack apresenta cada elemento da oferta separadamente com seu valor individual, depois mostra o total acumulado antes de revelar o preco real. Preco real deve ser dramaticamente menor que o Stack total. Cria percepcao de recebo muito mais do que pago. Regra: o investimento nao deve custar dinheiro - deve economizar dinheiro.", "priority": "HIGH", "confidence": 0.92, "tags": ["[HEURISTICA]", "OFERTA", "PRICING"], "chunks": [f"chunk_{SOURCE_ID}_085", f"chunk_{SOURCE_ID}_086"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[HEURISTICA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-012", "titulo": "Urgencia e Escassez - Gatilho Nao-Negociavel no Fechamento", "insight": "Se o prospect sai da apresentacao sem comprar, a chance de voltar cai para quase zero. Urgencia e escassez sao as duas ferramentas mais poderosas do marketing - oferta especial so disponivel durante a apresentacao e essencial para forcar decisao imediata. Nunca pular esta parte. Sem urgencia, a apresentacao e educativa mas nao converte.", "priority": "HIGH", "confidence": 0.93, "tags": ["[HEURISTICA]", "FECHAMENTO", "URGENCIA"], "chunks": [f"chunk_{SOURCE_ID}_088", f"chunk_{SOURCE_ID}_089"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[HEURISTICA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-013", "titulo": "Prolific Zone - Entre o Mainstream e o Nichissimo", "insight": "O posicionamento ideal esta na Prolific Zone: especifico o suficiente para nao competir com o mainstream, mas amplo o suficiente para ter audiencia. Exemplo: nao dieta, mas perder peso sem dieta bebendo cetona - causa polemica, atrai atencao, se diferencia. Mensagens polarizadoras dentro da Prolific Zone se espalham sozinhas.", "priority": "HIGH", "confidence": 0.88, "tags": ["[HEURISTICA]", "POSICIONAMENTO", "NICHO"], "chunks": [f"chunk_{SOURCE_ID}_019", f"chunk_{SOURCE_ID}_020"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[HEURISTICA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-014", "titulo": "Epiphany Bridge Script - 7 Etapas da Historia que Cria Crenca", "insight": "Estrutura: (1) Backstory - onde voce estava antes; (2) Desejo - o que voce queria; (3) O Muro - obstaculo intransponivel; (4) Epifania - o aha moment; (5) Plano - como voce agiu; (6) Conflito - obstaculos na jornada; (7) Achievement + Transformation - resultado e quem voce se tornou. Conta em 1a pessoa com emocao e conflito, termina com transformacao de identidade.", "priority": "HIGH", "confidence": 0.92, "tags": ["[METODOLOGIA]", "STORYTELLING", "COPYWRITING"], "chunks": [f"chunk_{SOURCE_ID}_060", f"chunk_{SOURCE_ID}_061", f"chunk_{SOURCE_ID}_062"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[METODOLOGIA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-015", "titulo": "Opportunity Switch vs Opportunity Stack - 2 Movimentos de Oferta", "insight": "Existem dois movimentos: (1) Opportunity Switch - mudar completamente o que o prospect faz (ex: sair de emprego para empreender); (2) Opportunity Stack - melhorar dentro do caminho ja escolhido (ex: ja empreende, adicionar funnels). O posicionamento muda dependendo de onde o prospect esta na jornada.", "priority": "HIGH", "confidence": 0.87, "tags": ["[MODELO-MENTAL]", "FUNIL", "POSICIONAMENTO"], "chunks": [f"chunk_{SOURCE_ID}_036", f"chunk_{SOURCE_ID}_037"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[MODELO-MENTAL]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-016", "titulo": "Email Epiphany Funnel - 4 Emails de Venda sem Webinar", "insight": "O Perfect Webinar pode ser quebrado em 4 emails: Email 1 - historia de origem (backstory + epifania da oportunidade); Email 2 - historia de crenca interna; Email 3 - historia de crenca externa; Email 4 - Stack + Pitch + Urgencia. Cada email conta uma Epiphany Bridge story especifica. Converte sem apresentacao ao vivo.", "priority": "HIGH", "confidence": 0.88, "tags": ["[METODOLOGIA]", "EMAIL", "FUNIL"], "chunks": [f"chunk_{SOURCE_ID}_108", f"chunk_{SOURCE_ID}_109"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[METODOLOGIA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-017", "titulo": "Attractive Character - 3 Elementos do Lider Carismatico", "insight": "O Attractive Character e construido sobre: (1) Backstory e falhas - imperfeicoes criam identificacao; (2) Parabolico - usa historias para ensinar; (3) Polaridade - posicoes claras e opinioes fortes. Perfeicao repele; vulnerabilidade controlada conecta. O Attractive Character e a razao pela qual pessoas seguem alem da informacao.", "priority": "HIGH", "confidence": 0.90, "tags": ["[FRAMEWORK]", "LIDERANCA", "BRANDING"], "chunks": [f"chunk_{SOURCE_ID}_011", f"chunk_{SOURCE_ID}_012"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[FRAMEWORK]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-018", "titulo": "Trial Closes - Micro-Compromissos ao Longo da Apresentacao", "insight": "Trial closes sao perguntas de compromisso espalhadas ao longo da apresentacao antes do pitch final: Isso faz sentido? Voce ve como funcionaria para voce? Cada sim cria momentum psicologico. 20 sims durante a apresentacao tornam o sim no pitch o comportamento mais consistente. Micro-compromissos preparam o sim final.", "priority": "HIGH", "confidence": 0.88, "tags": ["[HEURISTICA]", "FECHAMENTO", "PERSUASAO"], "chunks": [f"chunk_{SOURCE_ID}_087"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[HEURISTICA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-019", "titulo": "A Causa - Construir um Futuro que as Pessoas Querem Ajudar a Criar", "insight": "Todo movimento tem uma Causa maior do que o produto - uma visao de futuro que os seguidores querem contribuir para construir. A Causa une pessoas em torno de inimigo comum ou missao compartilhada. Identidade de grupo (Somos Funnel Hackers) cria tribo. Sem Causa, ha clientes; com Causa, ha movimento.", "priority": "HIGH", "confidence": 0.88, "tags": ["[FILOSOFIA]", "MOVIMENTO", "COMUNIDADE"], "chunks": [f"chunk_{SOURCE_ID}_016", f"chunk_{SOURCE_ID}_017"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[FILOSOFIA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-020", "titulo": "Publicar Diariamente - Voz Encontrada pela Consistencia", "insight": "Voz autentica nao vem de reflexao, vem de publicacao consistente. Publique sua mensagem diariamente (podcast, blog, video). Certeza vem da repeticao - voce fica mais certo a medida que ensina mais. Escolha a plataforma onde voce e mais natural - consistencia importa mais que o canal.", "priority": "MEDIUM", "confidence": 0.83, "tags": ["[HEURISTICA]", "CONTEUDO", "LIDERANCA"], "chunks": [f"chunk_{SOURCE_ID}_018"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[HEURISTICA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-021", "titulo": "One Thing - Webinar Ensina UMA Coisa com Alta Profundidade", "insight": "A apresentacao perfeita ensina UMA coisa, nao dez. Tentar provar muito divide atencao e enfraquece o Big Domino. A venda acontece quando a audiencia acredita completamente em UMA coisa fundamental. Profundidade em um ponto supera amplitude em muitos pontos.", "priority": "HIGH", "confidence": 0.90, "tags": ["[HEURISTICA]", "COPYWRITING", "WEBINAR"], "chunks": [f"chunk_{SOURCE_ID}_079", f"chunk_{SOURCE_ID}_080"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[HEURISTICA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-022", "titulo": "Analogia como Ferramenta de Crenca - E Como", "insight": "Quando apresentar conceito novo ou complexo, use a frase e como para conectar ao que a audiencia ja conhece. Analogias reduzem resistencia cognitiva e criam emocao ligada ao conhecido. Toda crenca nova precisa de uma ponte para o familiar.", "priority": "MEDIUM", "confidence": 0.83, "tags": ["[MODELO-MENTAL]", "STORYTELLING"], "chunks": [f"chunk_{SOURCE_ID}_053"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[MODELO-MENTAL]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-023", "titulo": "Persistencia - Primeira Tentativa Falha Nao E Sinal de Stop", "insight": "Sucesso em webinar e lancamentos vem de iteracao, nao perfeicao inicial. Liz Benny nao teve ninguem na primeira live mas faturou mais de 1M no primeiro ano. Regra: nunca parar apos uma tentativa, especialmente com resultado ruim. O processo de refinar E o que cria o resultado.", "priority": "MEDIUM", "confidence": 0.80, "tags": ["[FILOSOFIA]", "MENTALIDADE"], "chunks": [f"chunk_{SOURCE_ID}_103"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[FILOSOFIA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-024", "titulo": "Big Domino Statement - Formato de Crenca Central da Oferta", "insight": "Formato exato: Se eu conseguir fazer as pessoas acreditarem que [NOVA OPORTUNIDADE] e a chave para [RESULTADO DESEJADO] e que so e alcancavel atraves de [MINHA SOLUCAO], entao todas as outras objecoes se tornam irrelevantes e elas precisam comprar. Esse statement deve ser verdadeiro e isolar sua oferta no mercado.", "priority": "HIGH", "confidence": 0.95, "tags": ["[METODOLOGIA]", "COPYWRITING", "POSICIONAMENTO"], "chunks": [f"chunk_{SOURCE_ID}_048", f"chunk_{SOURCE_ID}_049"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[METODOLOGIA]", "timestamp": datetime.now().isoformat()},
  {"id": f"INS-{SOURCE_ID}-025", "titulo": "High-Ticket 4-Question Close - Fechamento por Perguntas", "insight": "Para ofertas high-ticket, o fechamento acontece por 4 perguntas: (1) O que voce mais quer? (2) O que te impede de ter isso agora? (3) Se voce pudesse superar isso, o que mudaria? (4) Quanto vale isso para voce? As respostas revelam motivacao, objecoes e valor percebido - fechamento acontece naturalmente.", "priority": "HIGH", "confidence": 0.88, "tags": ["[METODOLOGIA]", "FECHAMENTO", "HIGH-TICKET"], "chunks": [f"chunk_{SOURCE_ID}_096", f"chunk_{SOURCE_ID}_097"], "source_id": SOURCE_ID, "source_person": SOURCE_PERSON, "source_title": SOURCE_TITLE, "dna_tag": "[METODOLOGIA]", "timestamp": datetime.now().isoformat()},
]

print(f"Total insights: {len(insights)}")
high = sum(1 for i in insights if i["priority"] == "HIGH")
med = sum(1 for i in insights if i["priority"] == "MEDIUM")
print(f"HIGH: {high} | MEDIUM: {med}")

tags_count = {}
for ins in insights:
    tag = ins["dna_tag"]
    tags_count[tag] = tags_count.get(tag, 0) + 1
print("DNA distribution:", tags_count)

data = json.loads(INSIGHTS_PATH.read_text(encoding="utf-8"))
state = data.get("insights_state", {})
persons = state.get("persons", {})
if SOURCE_PERSON not in persons:
    persons[SOURCE_PERSON] = []
existing_ids = {i.get("id") for i in persons[SOURCE_PERSON]}
new_insights = [i for i in insights if i["id"] not in existing_ids]
persons[SOURCE_PERSON].extend(new_insights)
state["persons"] = persons
state.setdefault("change_log", []).append({
    "timestamp": datetime.now().isoformat(),
    "operation": "INSIGHT_EXTRACTION",
    "source_id": SOURCE_ID,
    "person": SOURCE_PERSON,
    "insights_added": len(new_insights)
})
data["insights_state"] = state
INSIGHTS_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Saved {len(new_insights)} insights to INSIGHTS-STATE.json")
print("PHASE 4 COMPLETE")
